name: Matrix Demo

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0 8.0]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
         dotnet-version: ${{ matrix.version}}
         
      - name: Build Solution
        run: dotnet build

      - name: Print matrix values
        run: |
          echo "Running on OS ${{ matrix.os}}"
          echo "Using .NET version: {{ matrix.version }}"
          
  post-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Post-build
        run: echo "Post-build message"
      
    
